### ISSUE TITLE
Duda

### ISSUE THREAD

**Issue by LuisRodesDAM** [LuisRodesDAM/ProgramacionDeServiciosYProcesosErrores#1]
Buenas tardes @jgarcia-gh  estoy intentando ponerme al dia con este módulo y no veo como desde intellij Idea hacer la subida a github.
No se si se hace configurando intellij o simplemente copiando y subiendo la carpeta directamente a github.
Gracias y saludos.

**Comment by LuisRodesDAM** [comment]
Vale ya esta, lo he subido directamente y voy a ver si desde intelli me sube los cambios o lo hago desde gitHubDesktop

**Comment by LuisRodesDAM** [comment]
Vale nada los cambios que hago en Intellij no los sube a github @jgarcia-gh no se como hacerlo o si se hace solo desde Visual Studio

**Comment by jgarcia-gh** [comment]
Hola, yo normalmente lo que hago es crear el repositorio en github, luego lo clono en mi ordenador en una carpeta, creo el proyecto de IntelliJ en esa carpeta y a partir de ahí subo los cambios con el cliente que utilices (Github desktop o similar). Otra opción es crear primero el proyecto de IntelliJ, luego mediante Github desktop o similar, crear un repositorio en la carpeta donde está el proyecto y por último configurarlo para que el remoto sea la URL del repositorio de Github. Para subir los cambios es necesario hacer commit y posteriormente push desde Github Desktop.

**Comment by LuisRodesDAM** [comment]
ok, a ver si el trabajo me deja y retomo el tema de nuevo.
